### ISSUE TITLE
how to train this model for my own dataset?

### ISSUE THREAD

**Issue by Sushmab27** [soCzech/TransNet#1]
I have to work on shot detection for  medical videos. what is the dataset format for this code.
After creating the dataset how to train the model.
answers to this query will be a great help for me.

**Comment by soCzech** [comment]
The network takes input of type `tf.uint8 ~ np.uint8` and shape `[batch_size, no_consecutive_frames, 27, 48, 3]` where `no_consecutive_frames=100` in our experiments (see [here](https://github.com/soCzech/TransNet/blob/master/transnet.py#L37)).

See [example.ipynb](https://github.com/soCzech/TransNet/blob/master/example.ipynb), how to do inference. For training the same format would be used. If something in [example.ipynb](https://github.com/soCzech/TransNet/blob/master/example.ipynb) is unclear, let me know.

For training details, see the paper [TransNet: A deep network for fast detection of common shot transitions](https://arxiv.org/abs/1906.03363).

The provided code does only inference for simplicity and clarity because training is highly dependent on your format of the data and type of augmentation you use.

**Comment by soCzech** [comment]
A new version with better performance has been released. It also contains training code.
See [github.com/soCzech/TransNetV2](https://github.com/soCzech/TransNetV2).
